### ISSUE TITLE
cắt EJS

### ISSUE THREAD

**Issue by truongduchuy910** [truongduchuy910/loaloa.me#7]
#### Branch 
Master
#### File
./models/public.js
./views/public/home
##### Chỉnh sửa file gửi xuống cho EJS nhận
tại hàm home, trong file ./models/public.js
phần render hiện tại là:
``` javascript
    res.render('public/pages/home')
```
giờ chỉnh sửa file gửi xuống ví dụ cho các hình dự án
``` javascript
    res.render('public/pages/home', {
        du_an: [
        ....
        ]
})
```
##### Tiến hành cắt EJS với biến đã gửi xuống
Ví dụ
``` javascript
    <%du_an.forEach(d => {
    %>
   <img class="col-4" src="<%=d.url%>">
    <%
    })%>
```

**Comment by baphuc2906** [comment]
i'm coding it
