### ISSUE TITLE
design pages

### ISSUE THREAD

**Issue by baphuc2906** [truongduchuy910/loaloa.me#8]
Cần design đầy đủ tính năng của loaloa.me

**Comment by truongduchuy910** [comment]
Do công việc đang con nhiều quá nên tập trung làm một cái landing page trước!

**Comment by baphuc2906** [comment]
> Do công việc đang còn nhiều quá nên tập trung làm một cái landing page trước!

rồi. clone duan.me ta về xem thử được không rồi t cắt ejs

**Comment by truongduchuy910** [comment]
Duan.me là chi
